apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-nfs-gateway-system
resources:
  - namespace.yaml
  - ../rbac
  - deployment.yaml
images:
  - name: ghcr.io/initialed85/longhorn-nfs-gateway
    newName: ghcr.io/initialed85/longhorn-nfs-gateway
    newTag: dev
