// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *LonghornNFSExport) DeepCopyInto(out *LonghornNFSExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *LonghornNFSExport) DeepCopy() *LonghornNFSExport {
	if in == nil {
		return nil
	}
	out := new(LonghornNFSExport)
	in.DeepCopyInto(out)
	return out
}

func (in *LonghornNFSExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LonghornNFSExportList) DeepCopyInto(out *LonghornNFSExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]LonghornNFSExport, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *LonghornNFSExportList) DeepCopy() *LonghornNFSExportList {
	if in == nil {
		return nil
	}
	out := new(LonghornNFSExportList)
	in.DeepCopyInto(out)
	return out
}

func (in *LonghornNFSExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LonghornNFSExportSpec) DeepCopyInto(out *LonghornNFSExportSpec) {
	*out = *in
	if in.MountOptions != nil {
		out.MountOptions = append([]string(nil), in.MountOptions...)
	}
	in.Helper.DeepCopyInto(&out.Helper)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.Handoff.DeepCopyInto(&out.Handoff)
}

func (in *LonghornNFSExportSpec) DeepCopy() *LonghornNFSExportSpec {
	if in == nil {
		return nil
	}
	out := new(LonghornNFSExportSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HelperSpec) DeepCopyInto(out *HelperSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
}

func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.AllowedCIDRs != nil {
		out.AllowedCIDRs = append([]string(nil), in.AllowedCIDRs...)
	}
}

func (in *HandoffSpec) DeepCopyInto(out *HandoffSpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.NativePodSelector != nil {
		out.NativePodSelector = make(map[string]string, len(in.NativePodSelector))
		for k, v := range in.NativePodSelector {
			out.NativePodSelector[k] = v
		}
	}
}

func (in *LonghornNFSExportStatus) DeepCopyInto(out *LonghornNFSExportStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	if in.Endpoint != nil {
		out.Endpoint = new(EndpointStatus)
		*out.Endpoint = *in.Endpoint
	}
	if in.Helper != nil {
		out.Helper = new(HelperStatus)
		*out.Helper = *in.Helper
	}
}
